<?php 

define( 'ACF_LITE', true );
require_once( get_template_directory() . '/vendor/advanced-custom-fields/acf.php' );
require_once( get_template_directory() . '/vendor/acf-repeater/acf-repeater.php' );

if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_pp-home',
		'title' => 'PP Home',
		'fields' => array (
			array (
				'key' => 'field_53d16531b9b95',
				'label' => 'Sections (Logged Out)',
				'name' => 'ppannounce_home_logout_sections',
				'type' => 'repeater',
				'sub_fields' => array (
					array (
						'key' => 'field_53d1655fb9b96',
						'label' => 'Section Title',
						'name' => 'section_title',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_53d166a9b9b97',
						'label' => 'Section ID',
						'name' => 'section_id',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'none',
						'maxlength' => '',
					),
					array (
						'key' => 'field_53d166b3b9b98',
						'label' => 'Section Content',
						'name' => 'section_content',
						'type' => 'wysiwyg',
						'column_width' => '',
						'default_value' => '',
						'toolbar' => 'full',
						'media_upload' => 'yes',
					),
				),
				'row_min' => 1,
				'row_limit' => '',
				'layout' => 'row',
				'button_label' => 'Add Row',
			),
			array (
				'key' => 'field_53d168bec531f',
				'label' => 'Sections (Logged In)',
				'name' => 'ppannounce_home_login_sections',
				'type' => 'repeater',
				'sub_fields' => array (
					array (
						'key' => 'field_53d168bec5320',
						'label' => 'Section Title',
						'name' => 'section_title',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_53d168bec5321',
						'label' => 'Section ID',
						'name' => 'section_id',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'none',
						'maxlength' => '',
					),
					array (
						'key' => 'field_53d168bec5322',
						'label' => 'Section Content',
						'name' => 'section_content',
						'type' => 'wysiwyg',
						'column_width' => '',
						'default_value' => '',
						'toolbar' => 'full',
						'media_upload' => 'yes',
					),
				),
				'row_min' => 1,
				'row_limit' => '',
				'layout' => 'row',
				'button_label' => 'Add Row',
			),
			array (
				'key' => 'field_53d1672fb9b99',
				'label' => 'Modals (Logged Out)',
				'name' => 'ppannounce_home_logout_modals',
				'type' => 'repeater',
				'sub_fields' => array (
					array (
						'key' => 'field_53d16872b9b9a',
						'label' => 'Modal Title',
						'name' => 'modal_title',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_53d16879b9b9b',
						'label' => 'Modal ID',
						'name' => 'modal_id',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'none',
						'maxlength' => '',
					),
					array (
						'key' => 'field_53d16883b9b9c',
						'label' => 'Modal Body',
						'name' => 'modal_body',
						'type' => 'wysiwyg',
						'column_width' => '',
						'default_value' => '',
						'toolbar' => 'full',
						'media_upload' => 'yes',
					),
					array (
						'key' => 'field_53d1688cb9b9d',
						'label' => 'Modal Footer',
						'name' => 'modal_footer',
						'type' => 'wysiwyg',
						'column_width' => '',
						'default_value' => '',
						'toolbar' => 'full',
						'media_upload' => 'yes',
					),
				),
				'row_min' => '',
				'row_limit' => '',
				'layout' => 'row',
				'button_label' => 'Add Row',
			),
			array (
				'key' => 'field_53d168dbc5323',
				'label' => 'Modals (Logged In)',
				'name' => 'ppannounce_home_login_modals',
				'type' => 'repeater',
				'sub_fields' => array (
					array (
						'key' => 'field_53d168dbc5324',
						'label' => 'Modal Title',
						'name' => 'modal_title',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array (
						'key' => 'field_53d168dbc5325',
						'label' => 'Modal ID',
						'name' => 'modal_id',
						'type' => 'text',
						'column_width' => '',
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'none',
						'maxlength' => '',
					),
					array (
						'key' => 'field_53d168dbc5326',
						'label' => 'Modal Body',
						'name' => 'modal_body',
						'type' => 'wysiwyg',
						'column_width' => '',
						'default_value' => '',
						'toolbar' => 'full',
						'media_upload' => 'yes',
					),
					array (
						'key' => 'field_53d168dbc5327',
						'label' => 'Modal Footer',
						'name' => 'modal_footer',
						'type' => 'wysiwyg',
						'column_width' => '',
						'default_value' => '',
						'toolbar' => 'full',
						'media_upload' => 'yes',
					),
				),
				'row_min' => '',
				'row_limit' => '',
				'layout' => 'row',
				'button_label' => 'Add Row',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_type',
					'operator' => '==',
					'value' => 'front_page',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'front-page.php',
					'order_no' => 0,
					'group_no' => 1,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
				0 => 'the_content',
			),
		),
		'menu_order' => 0,
	));
}
